site_name: Learning Bayes 30 Days
site_url: 
site_author: JW Tsai
nav:
    - Part 1:
        - Home: index.md
        - About: about.md
    - Part 2:
        - How to: howto.md
        - Jupyter: Untitled1.ipynb
    
theme: 
  name: readthedocs
  features:
    - navigation.sections
markdown_extensions:
    - extra
    - smarty
    - toc:
        permalink: []
    - admonition
    - def_list
    - footnotes
    - tables

plugins:
  - mkdocs-jupyter
  - search
  - autolinks
  - with-pdf

  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
