site_name: Learning Bayes 30 Days
site_url: 
site_author: JW Tsai
nav:
    - Preface: preface.md
    - Part 1 Introduction:
        - Day1
        - About: about.md
    - Part 2 linear model:
        - How to: howto.md
        - Jupyter: Untitled1.ipynb
    - Part 3 psychometric models:
        - FA
        
    
theme: 
  name: readthedocs
  features:
    - navigation.sections
markdown_extensions:
    - extra
    - smarty
    - toc:
        permalink: []
    - admonition
    - def_list
    - footnotes
    - tables

plugins:
  - mkdocs-jupyter
  - search
  - autolinks
  - pdf-export

  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
